In [1]:
import pandas as pd
import numpy as np
p = lambda x: print(str(x))

col_a = [1, 2, 3, "8", 9]
col_b = [3, 4, 6, 0, 7]
df = pd.DataFrame({"a": col_a, "b": col_b})


BlockManager
Items: Index(['a', 'b'], dtype='object')
Axis 1: RangeIndex(start=0, stop=5, step=1)
NumpyBlock: slice(0, 1, 1), 1 x 5, dtype: object
NumpyBlock: slice(1, 2, 1), 1 x 5, dtype: int64
<class 'numpy.ndarray'>
40
40
10111000111110011110010000101101111110010111111100000000000000001101100011111001111001000010110111111001011111110000000000000000111110001111100111100100001011011111100101111111000000000000000001011000111010011110010100101101111110010111111100000000000000001011100011111010111001000010110111111001011111110000000000000000
<U11
int32


C:\Users\Administrator\AppData\Local\Temp\ipykernel_2828\947813918.py:8: DeprecationWarning: DataFrame._data is deprecated and will be removed in a future version. Use public APIs instead.
  p(df._data)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_2828\947813918.py:9: DeprecationWarning: DataFrame._data is deprecated and will be removed in a future version. Use public APIs instead.
  p(type(df._data.blocks[0].values))
C:\Users\Administrator\AppData\Local\Temp\ipykernel_2828\947813918.py:10: DeprecationWarning: DataFrame._data is deprecated and will be removed in a future version. Use public APIs instead.
  p(df._data.blocks[0].values.data)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_2828\947813918.py:11: DeprecationWarning: DataFrame._data is deprecated and will be removed in a future version. Use public APIs instead.
  p(df._data.blocks[0].values.nbytes)
C:\Users\Administrator\AppData\Local\Temp\ipykernel_2828\947813918.py:12: DeprecationWarning: DataFrame._data is depr

In [1]:

p(df._data)
p(type(df._data.blocks[0].values))
p(df._data.blocks[0].values.data)
p(df._data.blocks[0].values.nbytes)
p(df._data.blocks[1].values.nbytes)
bytes_ = df._data.blocks[0].values.tobytes()
# print("".join(f"{byte:08b}" for byte in bytes_))
print("".join("{:08b}".format(byte) for byte in bytes_))

NameError: name 'p' is not defined

In [2]:
n = np.array(col_a)
p(n.dtype)
n = np.array(col_b)
p(n.dtype)
s = pd.Series(col_a)
s.dtype

<U11
int32


In [4]:
data = np.zeros((2,), dtype=[("A", "i4"), ("B", "f4"), ("C", "a10")])
data

array([(0, 0., b''), (0, 0., b'')],
      dtype=[('A', '<i4'), ('B', '<f4'), ('C', 'S10')])

In [16]:
df = pd.DataFrame.from_dict(

    dict([("A", [1, 2, 3]), ("B", [4, 5, 6])]),

    orient="index",

    columns=["one", "two", "three"],

)

df["i"] = df['one'][:1]
x =df.loc['B']["i"]
type(x)
print(x)
np.isnan(x)

nan


True

In [17]:
a = np.array([[1,0,1],[0,1,0]])
b = np.array([[0,0,0],[1,1,1]])
a ^ b

array([[1, 0, 1],
       [1, 0, 1]])

In [18]:
a | b

array([[1, 0, 1],
       [1, 1, 1]])

In [19]:
a = np.diag([1,2,3,4,5])
a.flat


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [21]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
             dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x[1]

('Fido', 3, 27.)